-   id: pipx
    name: pipx
    entry: pipx run
    language: python
    minimum_pre_commit_version: '2.9.2'
-   id: pipx-serial
    name: pipx-serial
    entry: pipx run
    require_serial: true
    language: python
    minimum_pre_commit_version: '2.9.2'
