version: 2
build:
  os: ubuntu-22.04
  tools: {}
  commands:
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - ~/.local/bin/uv tool install tox --with tox-uv -p 3.15 --managed-python
    - ~/.local/bin/tox run -e docs
