from typing import Any, Dict

# Versions of all packages possibly used in our tests
PKG: Dict[str, Dict[str, Any]] = {
    "ansible": {
        "spec": "ansible==2.9.13",
        "apps": [
            "ansible",
            "ansible-config",
            "ansible-connection",
            "ansible-console",
            "ansible-doc",
            "ansible-galaxy",
            "ansible-inventory",
            "ansible-playbook",
            "ansible-pull",
            "ansible-test",
            "ansible-vault",
        ],
        "apps_of_dependencies": [],
    },
    "awscli": {
        "spec": "awscli==1.18.168",
        "apps": [
            "aws",
            "aws.cmd",
            "aws_bash_completer",
            "aws_completer",
            "aws_zsh_completer.sh",
        ],
        "apps_of_dependencies": [
            "jp.py",
            "pyrsa-decrypt",
            "pyrsa-encrypt",
            "pyrsa-keygen",
            "pyrsa-priv2pub",
            "pyrsa-sign",
            "pyrsa-verify",
            "rst2html.py",
            "rst2html4.py",
            "rst2html5.py",
            "rst2latex.py",
            "rst2man.py",
            "rst2odt.py",
            "rst2odt_prepstyles.py",
            "rst2pseudoxml.py",
            "rst2s5.py",
            "rst2xetex.py",
            "rst2xml.py",
            "rstpep2html.py",
        ],
    },
    "b2": {
        "spec": "b2==2.0.2",
        "apps": ["b2"],
        "apps_of_dependencies": ["chardetect", "tqdm"],
    },
    "beancount": {
        "spec": "beancount==2.3.3",
        "apps": [
            "bean-bake",
            "bean-check",
            "bean-doctor",
            "bean-example",
            "bean-extract",
            "bean-file",
            "bean-format",
            "bean-identify",
            "bean-price",
            "bean-query",
            "bean-report",
            "bean-sql",
            "bean-web",
            "treeify",
            "upload-to-sheets",
        ],
        "apps_of_dependencies": [
            "bottle.py",
            "chardetect",
            "py.test",
            "pyrsa-decrypt",
            "pyrsa-encrypt",
            "pyrsa-keygen",
            "pyrsa-priv2pub",
            "pyrsa-sign",
            "pyrsa-verify",
            "pytest",
        ],
    },
    "beets": {
        "spec": "beets==1.4.9",
        "apps": ["beet"],
        "apps_of_dependencies": [
            "mid3cp",
            "mid3iconv",
            "mid3v2",
            "moggsplit",
            "mutagen-inspect",
            "mutagen-pony",
            "unidecode",
        ],
    },
    "black": {
        "spec": "black==20.8b1",
        "apps": ["black", "black-primer", "blackd"],
        "apps_of_dependencies": [],
    },
    "cactus": {
        "spec": "cactus==3.3.3",
        "apps": ["cactus"],
        "apps_of_dependencies": [
            "asadmin",
            "bundle_image",
            "cfadmin",
            "cq",
            "cwutil",
            "django-admin.py",
            "dynamodb_dump",
            "dynamodb_load",
            "elbadmin",
            "fetch_file",
            "glacier",
            "instance_events",
            "keyring",
            "kill_instance",
            "launch_instance",
            "list_instances",
            "lss3",
            "markdown2",
            "mturk",
            "pyami_sendmail",
            "route53",
            "s3put",
            "sdbadmin",
            "taskadmin",
        ],
    },
    "chert": {
        "spec": "chert==19.1.0",
        "apps": ["chert"],
        "apps_of_dependencies": ["ashes", "ashes.py", "markdown_py"],
    },
    "cloudtoken": {
        "spec": "cloudtoken==0.1.707",
        "apps": ["cloudtoken", "cloudtoken.app", "cloudtoken_proxy.sh", "awstoken"],
        "apps_of_dependencies": ["chardetect", "flask", "jp.py", "keyring"],
    },
    "coala": {
        "spec": "coala==0.11.0",
        "apps": [
            "coala",
            "coala-ci",
            "coala-delete-orig",
            "coala-format",
            "coala-json",
        ],
        "apps_of_dependencies": ["chardetect", "pygmentize", "unidiff"],
    },
    "cookiecutter": {
        "spec": "cookiecutter==1.7.2",
        "apps": ["cookiecutter"],
        "apps_of_dependencies": ["chardetect", "slugify"],
    },
    "cython": {
        "spec": "cython==0.29.21",
        "apps": ["cygdb", "cython", "cythonize"],
        "apps_of_dependencies": [],
    },
    "datasette": {
        "spec": "datasette==0.50.2",
        "apps": ["datasette"],
        "apps_of_dependencies": ["hupper", "pint-convert" "uvicorn"],
    },
    "diffoscope": {
        "spec": "diffoscope==154",
        "apps": ["diffoscope"],
        "apps_of_dependencies": [],
    },
    "doc2dash": {
        "spec": "doc2dash==2.3.0",
        "apps": ["doc2dash"],
        "apps_of_dependencies": [
            "chardetect",
            "pybabel",
            "pygmentize",
            "rst2html.py",
            "rst2html4.py",
            "rst2html5.py",
            "rst2latex.py",
            "rst2man.py",
            "rst2odt.py",
            "rst2odt_prepstyles.py",
            "rst2pseudoxml.py",
            "rst2s5.py",
            "rst2xetex.py",
            "rst2xml.py",
            "rstpep2html.py",
            "sphinx-apidoc",
            "sphinx-autogen",
            "sphinx-build",
            "sphinx-quickstart",
        ],
    },
    "doitlive": {
        "spec": "doitlive==4.3.0",
        "apps": ["doitlive"],
        "apps_of_dependencies": [],
    },
    "gdbgui": {
        "spec": "gdbgui==0.14.0.1",
        "apps": ["gdbgui"],
        "apps_of_dependencies": ["flask", "pygmentize"],
    },
    "gns3-gui": {"spec": "gns3-gui==2.2.15"},
    "grow": {"spec": "grow==1.0.0a10"},
    "guake": {"spec": "guake==3.7.0"},
    "gunicorn": {"spec": "gunicorn==20.0.4"},
    "howdoi": {"spec": "howdoi==2.0.7"},
    "httpie": {"spec": "httpie==2.3.0"},
    "hyde": {"spec": "hyde==0.8.9"},
    "ipython": {"spec": "ipython==7.16.1"},
    "isort": {"spec": "isort==5.6.4"},
    "jaraco-financial": {
        "spec": "jaraco.financial==2.0",
        "apps": [
            "clean-msmoney-temp",
            "fix-qif-date-format",
            "launch-in-money",
            "ofx",
            "record-document-hashes",
        ],
        "apps_of_dependencies": ["keyring", "chardetect", "calc-prorate"],
    },
    "jupyter": {"spec": "jupyter==1.0.0"},
    "kaggle": {"spec": "kaggle==1.5.9"},
    "kibitzr": {"spec": "kibitzr==6.0.0"},
    "klaus": {"spec": "klaus==1.5.2"},
    "kolibri": {"spec": "kolibri==0.14.3"},
    "lektor": {"spec": "Lektor==3.2.0"},
    "localstack": {"spec": "localstack==0.12.1"},
    "mackup": {"spec": "mackup==0.8.29"},  # ONLY FOR mac, linux
    "magic-wormhole": {"spec": "magic-wormhole==0.12.0"},
    "mayan-edms": {"spec": "mayan-edms==3.5.2"},
    "mkdocs": {
        "spec": "mkdocs==1.1.2",
        "apps": ["mkdocs"],
        "apps_of_dependencies": [
            "livereload",
            "futurize",
            "pasteurize",
            "nltk",
            "tqdm",
            "markdown_py",
        ],
    },
    "mycli": {"spec": "mycli==1.22.2"},
    "nikola": {"spec": "nikola==8.1.1"},
    "nox": {"spec": "nox==2020.8.22"},
    "pelican": {"spec": "pelican==4.5.0"},
    "platformio": {"spec": "platformio==5.0.1"},
    "ppci": {"spec": "ppci==0.5.8"},
    "prosopopee": {"spec": "prosopopee==1.1.3"},
    "ptpython": {"spec": "ptpython==3.0.7"},
    "pycowsay": {
        "spec": "pycowsay==0.0.0.1",
        "apps": ["pycowsay"],
        "apps_of_dependencies": [],
    },
    "pylint": {
        "spec": "pylint==2.3.1",
        "apps": ["epylint", "pylint", "pyreverse", "symilar"],
        "apps_of_dependencies": ["isort"],
    },
    "retext": {"spec": "ReText==7.1.0"},
    "robotframework": {"spec": "robotframework==3.2.2"},
    "shell-functools": {"spec": "shell-functools==0.3.0"},
    "speedtest-cli": {"spec": "speedtest-cli==2.1.2"},
    "sphinx": {"spec": "Sphinx==3.2.1"},
    "sqlmap": {"spec": "sqlmap==1.4.10"},
    "streamlink": {"spec": "streamlink==1.7.0"},
    "taguette": {"spec": "taguette==0.9.2"},
    "term2048": {"spec": "term2048==0.2.7"},
    "tox-ini-fmt": {"spec": "tox-ini-fmt==0.5.0"},
    "visidata": {"spec": "visidata==2.0.1"},
    "vulture": {"spec": "vulture==2.1"},
    "weblate": {"spec": "Weblate==4.3.1"},
    "youtube-dl": {"spec": "youtube-dl==2020.9.20"},
    "zeo": {"spec": "ZEO==5.2.2"},
}
