from typing import Any, Dict

# Versions of all packages possibly used in our tests
PKG: Dict[str, Dict[str, Any]] = {
    "ansible": {"spec": "ansible==2.9.13"},
    "awscli": {"spec": "awscli==1.18.168"},
    "b2": {"spec": "b2==2.0.2"},
    "beancount": {"spec": "beancount==2.3.3"},
    "beets": {"spec": "beets==1.4.9"},
    "black": {"spec": "black==20.8b1"},
    "cactus": {"spec": "cactus==3.3.3"},
    "chert": {"spec": "chert==19.1.0"},
    "cloudtoken": {"spec": "cloudtoken==0.1.707"},
    "coala": {"spec": "coala==0.11.0"},
    "cookiecutter": {"spec": "cookiecutter==1.7.2"},
    "cython": {"spec": "cython==0.29.21"},
    "datasette": {"spec": "datasette==0.50.2"},
    "diffoscope": {"spec": "diffoscope==154"},
    "doc2dash": {"spec": "doc2dash==2.3.0"},
    "doitlive": {"spec": "doitlive==4.3.0"},
    "gdbgui": {"spec": "gdbgui==0.14.0.1"},
    "gns3-gui": {"spec": "gns3-gui==2.2.15"},
    "grow": {"spec": "grow==1.0.0a10"},
    "guake": {"spec": "guake==3.7.0"},
    "gunicorn": {"spec": "gunicorn==20.0.4"},
    "howdoi": {"spec": "howdoi==2.0.7"},
    "httpie": {"spec": "httpie==2.3.0"},
    "hyde": {"spec": "hyde==0.8.9"},
    "ipython": {"spec": "ipython==7.16.1"},
    "isort": {"spec": "isort==5.6.4"},
    "jaraco-financial": {
        "spec": "jaraco.financial==2.0",
        "apps": [
            "clean-msmoney-temp",
            "fix-qif-date-format",
            "launch-in-money",
            "ofx",
            "record-document-hashes",
        ],
        "apps_of_dependencies": ["keyring", "chardetect", "calc-prorate"],
    },
    "jupyter": {"spec": "jupyter==1.0.0"},
    "kaggle": {"spec": "kaggle==1.5.9"},
    "kibitzr": {"spec": "kibitzr==6.0.0"},
    "klaus": {"spec": "klaus==1.5.2"},
    "kolibri": {"spec": "kolibri==0.14.3"},
    "lektor": {"spec": "Lektor==3.2.0"},
    "localstack": {"spec": "localstack==0.12.1"},
    "mackup": {"spec": "mackup==0.8.29"},  # ONLY FOR mac, linux
    "magic-wormhole": {"spec": "magic-wormhole==0.12.0"},
    "mayan-edms": {"spec": "mayan-edms==3.5.2"},
    "mkdocs": {
        "spec": "mkdocs==1.1.2",
        "apps": ["mkdocs"],
        "apps_of_dependencies": [
            "livereload",
            "futurize",
            "pasteurize",
            "nltk",
            "tqdm",
            "markdown_py",
        ],
    },
    "mycli": {"spec": "mycli==1.22.2"},
    "nikola": {"spec": "nikola==8.1.1"},
    "nox": {"spec": "nox==2020.8.22"},
    "pelican": {"spec": "pelican==4.5.0"},
    "platformio": {"spec": "platformio==5.0.1"},
    "ppci": {"spec": "ppci==0.5.8"},
    "prosopopee": {"spec": "prosopopee==1.1.3"},
    "ptpython": {"spec": "ptpython==3.0.7"},
    "pycowsay": {"spec": "pycowsay==0.0.0.1", "apps": ["pycowsay"]},
    "pylint": {"spec": "pylint==2.3.1"},
    "retext": {"spec": "ReText==7.1.0"},
    "robotframework": {"spec": "robotframework==3.2.2"},
    "shell-functools": {"spec": "shell-functools==0.3.0"},
    "speedtest-cli": {"spec": "speedtest-cli==2.1.2"},
    "sphinx": {"spec": "Sphinx==3.2.1"},
    "sqlmap": {"spec": "sqlmap==1.4.10"},
    "streamlink": {"spec": "streamlink==1.7.0"},
    "taguette": {"spec": "taguette==0.9.2"},
    "term2048": {"spec": "term2048==0.2.7"},
    "tox-ini-fmt": {"spec": "tox-ini-fmt==0.5.0"},
    "visidata": {"spec": "visidata==2.0.1"},
    "vulture": {"spec": "vulture==2.1"},
    "weblate": {"spec": "Weblate==4.3.1"},
    "youtube-dl": {"spec": "youtube-dl==2020.9.20"},
    "zeo": {"spec": "ZEO==5.2.2"},
}
