name: Create tests package lists for offline tests
on:
  workflow_dispatch:
concurrency:
  group: create-tests-package-lists-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  create_package_lists:
    name: Create package lists
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.13", "3.12", "3.11", "3.10"]
        include:
          - os: macos-latest
            python-version: "3.13"
          - os: windows-latest
            python-version: "3.13"
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install nox
        run: python -m pip install nox
      - name: Create lists
        run: nox --non-interactive --session create_test_package_list-${{ matrix.python-version }} -- ./new_tests_packages
      - name: Store reports as artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: lists-${{ matrix.os }}-${{ matrix.python-version }}
          path: ./new_tests_packages
