name: Release
on:
  push:
    tags:
      - "*.*.*"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  default-python: "3.14"
jobs:
  build-package:
    name: Build pipx package
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: "${{ github.ref_name }}"
          persist-credentials: false
      - name: Set up Python ${{ env.default-python }}
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ env.default-python }}
      - name: Build sdist and wheel
        run: |
          pip install build
          python -m build
      - name: Upload distributions
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dist
          path: dist/
  pypi-publish:
    name: Publish pipx to PyPI
    needs: build-package
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/pipx
    permissions:
      id-token: write
    steps:
      - name: Download distributions
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: dist
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
  create-release:
    name: Create a release on GitHub's UI
    needs: pypi-publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Create release
        run: |
          gh release create --repo pypa/pipx "${RELEASE_TAG}" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ github.ref_name }}
  upload-zipapp:
    name: Upload zipapp to GitHub Release
    needs: create-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: "${{ github.ref_name }}"
          persist-credentials: false
      - name: Set up Python ${{ env.default-python }}
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ env.default-python }}
      - name: Install tox
        run: pip install tox
      - name: Build zipapp
        run: tox run -e zipapp
      - name: Upload to release
        run: |
          gh release upload --repo pypa/pipx "${RELEASE_TAG}" pipx.pyz
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ github.ref_name }}
